# Site settings
title: Sharpening the Saw until it Vanishes
email: cfhoyuk.reccos.nelg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tips for better life, especially in tech
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://genkisugimoto.com"
twitter_username: GenkiSugimoto
github_username:  Genki-S

# Build settings
markdown: kramdown
